server:
  port: 9090
##日志
logging:
  level:
    root: info
spring:
  elasticsearch:
    rest:
      uris: http://127.0.0.1:9200
      username: elastic
      password: 123456
  session:
    store-type: none
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 6000
    password:
    jedis:
      pool:
        max-wait:
        min-idle: 0
        max-idle: 8
        max-active: 8